# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=9)),
                ('addname', models.CharField(max_length=9)),
                ('addres', models.CharField(max_length=100)),
                ('addtel', models.BigIntegerField()),
                ('addpost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='carts',
            fields=[
                ('causname', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cartsid', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='indent',
            fields=[
                ('inname', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('indsellid', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='indentss',
            fields=[
                ('inid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('inname', models.CharField(max_length=9)),
                ('inaddres', models.CharField(max_length=100)),
                ('inaddtel', models.BigIntegerField()),
                ('inaddpost', models.IntegerField()),
                ('indsellid', models.BigIntegerField()),
                ('insellname', models.CharField(max_length=50)),
                ('insellimg', models.CharField(max_length=200)),
                ('inselljiage', models.IntegerField()),
                ('insellcolor', models.CharField(max_length=10, null=True)),
                ('insellsize', models.CharField(max_length=20, null=True)),
                ('insellnum', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('sellid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sellname', models.CharField(max_length=50)),
                ('sellimg', models.CharField(max_length=200)),
                ('selljiage', models.IntegerField()),
                ('sellcolor', models.CharField(max_length=10, null=True)),
                ('sellsize', models.CharField(max_length=20, null=True)),
                ('sellnum', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='us',
            fields=[
                ('username', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('usertel', models.BigIntegerField()),
                ('password', models.CharField(max_length=17)),
            ],
        ),
    ]
